#!/usr/bin/env python
# -*- coding: utf-8 -*-

from botocore.config import Config

BOTO3_CONFIG = Config(
    retries={
        "max_attempts": 15,
        "mode": "standard",
    }
)

PLAID_WEBHOOK_TYPE_BALANCE = "BALANCE"
PLAID_WEBHOOK_TYPE_TRANSACTIONS = "TRANSACTIONS"
PLAID_WEBHOOK_TYPE_LIABILITIES = "LIABILITIES"
PLAID_WEBHOOK_TYPE_HOLDINGS = "HOLDINGS"
PLAID_WEBHOOK_TYPE_INVESTMENTS_TRANSACTIONS = "INVESTMENTS_TRANSACTIONS"

PLAID_WEBHOOK_CODE_INITIAL_UPDATE = "INITIAL_UPDATE"
PLAID_WEBHOOK_CODE_TRANSACTIONS_REMOVED = "TRANSACTIONS_REMOVED"
PLAID_WEBHOOK_CODE_SYNC_UPDATES_AVAILABLE = "SYNC_UPDATES_AVAILABLE"
PLAID_WEBHOOK_CODE_HISTORICAL_UPDATE = "HISTORICAL_UPDATE"
PLAID_WEBHOOK_CODE_DEFAULT_UPDATE = "DEFAULT_UPDATE"

# Maximum number of transactions to return per sync call
PLAID_TRANSACTION_SYNC_COUNT_MAX = 500

PLAID_INVESTMENTS_TRANSACTIONS_COUNT_MAX = 500

DYNAMODB_EVENT_SOURCE = "aws:dynamodb"
DYNAMODB_EVENT_TYPE_INSERT = "INSERT"
DYNAMODB_EVENT_TYPE_MODIFY = "MODIFY"
DYNAMODB_EVENT_TYPE_REMOVE = "REMOVE"

SQS_EVENT_SOURCE = "aws:sqs"

# Maximum of messages SQS supports sending in a batch
SQS_SEND_MESSAGE_BATCH_MAX = 10

# DynamoDB attribute name for the Plaid access token
TOKEN_ATTRIBUTE_NAME = "access_token"

# DynamoDB attribute name for the cursor value
CURSOR_ATTRIBUTE_NAME = "cursor"
